Feature: Canvas

Scenario: Creating a canvas
  Given c = Canvas(10, 20)
  Then c.width == 10
    And c.height == 20
    And every pixel of c is color(0, 0, 0)

Scenario: Writing pixels to a canvas
  Given c = Canvas(10, 20)
    And red = Color(1, 0, 0)
  When write_pixel(c, 2, 3, red)
  Then pixel_at(c, 2, 3) == red

#Scenario: Constructing the PPM header
#  Given c = Canvas(5, 3)
#  When ppm = canvas_to_ppm(c)
#  Then lines 1-4 of ppm are
#    """
#    P6
#    # Generated by OpenCV 4.2.0
#    5 3
#    255
#    """

Scenario: Constructing the PPM pixel data
  I tweaked this one as we're not actually doing file reading here
  Given c = Canvas(5, 3)
    And c1 = Color(1.5, 0, 0)
    And c2 = Color(0, 0.5, 0)
    And c3 = Color(-0.5, 0, 1)
  When write_pixel(c, 0, 0, c1)
    And write_pixel(c, 2, 1, c2)
    And write_pixel(c, 4, 2, c3)
    And ppm = canvas_to_ppm(c)
  Then the body of ppm is 
    """
    255 0 0 0 0 0 0 0 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 128 0 0 0 0 0 0 0
    0 0 0 0 0 0 0 0 0 0 0 0 0 0 255
    """
